### ISSUE TITLE
Jitpack or MavenCentral?

### ISSUE THREAD

**Issue by psh** [psh/kotlin-state-machine#11]
Where to publish this library?

**Comment by psh** [comment]
https://maven.apache.org/repository/guide-central-repository-upload.html

**Comment by psh** [comment]
https://central.sonatype.org/publish/publish-guide/

https://central.sonatype.org/publish/publish-gradle/

**Comment by ged** [comment]
I don't know which is better, but I'd love to use this library for a current project. Any idea when/if you'll publish soon?
